require:
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec
  - rubocop-packaging
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - tmp/**/*
    - gemfiles/*
    - vendor/**/*

Metrics/BlockLength:
  IgnoredMethods: ['describe']
