name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ matrix.ruby }} - ${{ matrix.gemfile }}
    strategy:
      matrix:
        ruby:
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
          - 'truffleruby'
        gemfile:
          - 'activemodel_6.1'
          - 'activemodel_7.0'
          - 'activemodel_7.1'
          - 'activemodel_main'
        exclude:
          - ruby: '3.0'
            gemfile: 'activemodel_main'

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Lint via Rubocop
        run: bundle exec rubocop

      - name: Run tests
        run: bundle exec rspec

      - name: Report to Code Climate
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
