name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
    
      - name: Install dependencies
        run: bundle install

      - name: Appraisal
        run: bundle exec appraisal install
        run: bundle exec appraisal rspec

      - name: Run tests
        run: bundle exec rspec

      - name: Code Climate
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: 89848be69d8cf9080722c0781bddcec13fe8cc86cd3c410f500bc8811b28dbfc
